#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pathname'

source_path = File.expand_path("#{Pathname.new(__FILE__).dirname}/../lib")
$LOAD_PATH << source_path

require 'goggleme'

Goggleme::Main.start(ARGV)
